output "certificate" {
  description = "PEM-encoded Origin CA certificate."
  value       = cloudflare_origin_ca_certificate.this.certificate
}

output "generated" {
  description = "Whether the module generated a key and CSR internally (true when input csr was null)."
  value       = local.should_generate_csr
  sensitive   = true
}

output "csr" {
  description = "CSR used for the request (input)."
  value       = var.csr
  sensitive   = true
}

output "generated_csr_pem" {
  description = "CSR generated by the module when no csr was provided (null otherwise)."
  value       = local.should_generate_csr ? tls_cert_request.generated[0].cert_request_pem : null
  sensitive   = true
}

output "generated_private_key_pem" {
  description = "Private key generated by the module when no csr was provided (null otherwise). Handle securely."
  value       = local.should_generate_csr ? local.generated_private_key_pem : null
  sensitive   = true
}

output "expires_on" {
  description = "Certificate expiration timestamp."
  value       = try(cloudflare_origin_ca_certificate.this.expires_on, null)
}

output "id" {
  description = "Origin CA certificate ID."
  value       = cloudflare_origin_ca_certificate.this.id
}

output "hostnames" {
  description = "Hostnames included in the certificate."
  value       = var.hostnames
}

output "request_type" {
  description = "Origin CA request type (origin-ecc or origin-rsa)."
  value       = var.request_type
}

## Note: Root CA certificate and generated private key can be obtained outside of Terraform if needed.
