# output "worker_maintenance_route_id" {
#   value       = module.worker_maintenance.worker_route_id
#   description = "Worker maintenance route ID"
# }

# output "image_variant_ids" {
#   value       = module.media_transformations.variant_ids
#   description = "Created image variant IDs"
# }

output "origin_ca_certificate_id" {
  value       = module.origin_ca.id
  description = "Origin CA certificate ID"
}

output "origin_ca_certificate_expires_on" {
  value       = module.origin_ca.expires_on
  description = "When the Origin CA certificate expires"
}

output "origin_ca_certificate_pem" {
  value       = module.origin_ca.certificate
  description = "PEM-encoded Origin CA certificate"
  sensitive   = true
}

output "origin_ca_generated" {
  value       = module.origin_ca.generated
  description = "Whether the module generated a key and CSR (true when no CSR input was provided)."
  sensitive   = true
}

# The module can expose generated CSR/private key as sensitive outputs for advanced workflows.
# Consider writing them to a secure secret store rather than outputting them.
# output "origin_ca_generated_csr_pem" {
#   value       = module.origin_ca.generated_csr_pem
#   description = "CSR generated by the module (if any)."
#   sensitive   = true
# }
# output "origin_ca_generated_private_key_pem" {
#   value       = module.origin_ca.generated_private_key_pem
#   description = "Private key generated by the module (if any). Handle securely."
#   sensitive   = true
# }
